version: '3.9'
services:
  web:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - ./python-search
    links:
    - mongo
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
    ports:
      - "27017:27017" 
volumes:
  mongo-data:
  mongo-configdb: